name: Test CRC CI
on:
  push:
    branches:
      - main

jobs:
  crc-create:
    runs-on: ubuntu-latest
    container:
      image: quay.io/crcont/crc-cloud
      env:
        WORKING_MODE: C
        PULL_SECRET: ${{ secrets.PULL_SECRET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-west-2
      volumes: crc-workdir:/workdir



