apiVersion: v1
kind: Namespace
metadata:
  name: test

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: test
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged:stable-alpine
          ports:
            - name: http
              containerPort: 8080

