name: Test CRC CI
on:
  push:
    branches:
      - main

jobs:
  crc-create:
    runs-on: ubuntu-latest
    steps:
    - name: Create Workdir
      run: mkdir workdir
    - name: Pull CRC
      run: docker pull quay.io/crcont/crc-cloud:latest
    - name: Run CRC
      run: |
        docker run -v workdir:/workdir \
          -e WORKING_MODE=C \
          -e PULL_SECRET="${{ secrets.PULL_SECRET }}" \
          -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }} \
          -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          -e AWS_DEFAULT_REGION=us-west-2 \
          quay.io/crcont/crc-cloud
    



