name: Test CRC CI
on:
  push:
    branches:
      - main

jobs:
  crc-create:
    runs-on: ubuntu-latest
    steps:
    - name: Install oc
      uses: redhat-actions/oc-installer@v1
      with:
        oc_version: latest
    - name: Run JQ
      run: jq
    

