on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.comment.body == 'mimmo'}} 
    runs-on: ubuntu-latest
    steps:
      - name: echo
        env:
          MESSAGE: ${{github.event.comment.body}}
        run: echo "comment $MESSAGE!"  