on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: contains(github.event.comment.body, '/ocp-test') && contains(github.event.comment.html_url, '/pull/')
    runs-on: ubuntu-latest
    steps:
      - name: oc login
        continue-on-error: true
        run: |
          oc login  --insecure-skip-tls-verify -u kubeadmin -p kubeadmin https://api.35.166.164.246.nip.io
          echo $KUBECONFIG
          which yq

