on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: contains(github.event.comment.body, '/ocp-test') && contains(github.event.comment.html_url, '/pull/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install OC CLI
      uses: redhat-actions/oc-installer@v1
      with:
        oc_version: latest
    - uses: actions/checkout@v2
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: tsebastiani/krkn
    - name: oc login
      run: oc login --insecure-skip-tls-verify -u kubeadmin -p kubeadmin https://api.35.92.104.60.nip.io:6443
    - name: ls
      run: ls -al
    - name: Setup kraken dependencies
      run:  pip install -r requirements.txt
    - name: Test app outage scenario
      env:
        DEPLOYMENT_NAME: test-nginx
      run: |
        echo "test_app_outages" > ./CI/tests/my_tests
        yq -i '.kraken.port="8081"' CI/config/common_test_config.yaml
        yq -i '.kraken.signal_address="0.0.0.0"' CI/config/common_test_config.yaml
        yq -i '.application_outage.pod_selector={"app":"${{ env.DEPLOYMENT_NAME}}"}' CI/scenarios/app_outage.yaml
        ./CI/run.sh
    - name: Test container failure
      env:
        DEPLOYMENT_NAME: test-nginx
      run: |
        echo "test_container" > ./CI/tests/my_tests
        ./CI/run.sh
    - name: Test CPU hog
      env:
        DEPLOYMENT_NAME: test-nginx
      run: |
          echo "test_cpu_hog_gh" > ./CI/tests/my_tests
          ./CI/run.sh
    - name: cat result
      run: cat CI/out/test_cpu_hog.out
    - name: cat config
      run: cat CI/config/litmus_config.yaml

