on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: contains(github.event.comment.body, '/ocp-test') && contains(github.event.comment.html_url, '/pull/')
    runs-on: ubuntu-latest
    steps:
      - name: oc login
        continue-on-error: true
        run: |
          which python | true
          which python3.9 | true
          
