on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: contains(github.event.comment.body, 'ocptest') && contains(github.event.comment.html_url, '/pull/')
    runs-on: ubuntu-latest
    steps:
      - name: Install oc
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: latest
      - name: Create Workdir
        run: mkdir workdir
      - uses: webiny/action-post-run@3.0.0
        name: Teardown CRC (Post Action)
        id: post-run-command
        with:
          run: |
            docker run -v "$(pwd)/workdir:/workdir" \
            -e WORKING_MODE=T \
            -e TEARDOWN_RUN_ID=crc \
            -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
            -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
            -e AWS_DEFAULT_REGION=us-west-2 \
            quay.io/crcont/crc-cloud
      - name: Run CRC
        env:
          PULL_SECRET: ${{ secrets.PULL_SECRET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
            docker run -v $(pwd)/workdir:/workdir \
            -e WORKING_MODE=C \
            -e PULL_SECRET="$PULL_SECRET" \
            -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
            -e AWS_DEFAULT_REGION=us-west-2 \
            -e CREATE_RUN_ID=crc \
            quay.io/crcont/crc-cloud
      - name: Fail
        run: exit 1
