on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: contains(github.event.comment.body, 'ocptest') && contains(github.event.comment.html_url, '/pull/')
    runs-on: ubuntu-latest
    steps:
      - uses: webiny/action-post-run@3.0.0
        id: post-run-command
        with:
          run: echo "this thing works!"
      - name: will fail
        run: exit 1