on: issue_comment

jobs:
  check_user:
    # This job only runs for pull request comments
    name: check user
    env:
      USERS: ${{vars.USERS}}
    if: contains(github.event.comment.body, '/ocp-test') && contains(github.event.comment.html_url, '/pull/')
    runs-on: ubuntu-latest
    steps:
      - name: Check out Kraken
        uses: actions/checkout@v3
      - name: ls
        run: ls -al .github
      - name: test
        run: |
          for i in `echo $USERS`
          do
            echo "SONGO IO:-${i/$'\n'}-"
          done
      - name: Check User
        run: |
          for name in `echo $USERS`
          do 
            if [ $name == "${{github.event.sender.login}}" ]
            then
              exit 0
            fi
          done
          echo "user ${{github.event.sender.login}} is not allowed to run functional tests Action"
          exit 1
  
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    needs:
      - check_user
    if: contains(github.event.comment.body, '/ocp-test') && contains(github.event.comment.html_url, '/pull/')
    runs-on: ubuntu-latest
    steps:
      - name: Check out Kraken
        uses: actions/checkout@v3
      - name: ls
        run: ls -al .github
      - name: Check User
        run: |
          for name in `cat .github/users.txt`
          do 
            if [ $name == "${{github.event.sender.login}}" ]
            then
              exit 0
            fi
          done
          echo "user ${{github.event.sender.login}} is not allowed to run functional tests Action"
          exit 1
