on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: contains(github.event.comment.body, '/mauro') && contains(github.event.comment.html_url, '/pull/')
    runs-on: ubuntu-latest
    steps:
      - name: Check out Kraken
        uses: actions/checkout@v3
      - name: ls
        run: ls -al .github
      - name: Check User
        run: |
          for name in `cat .github/users.txt`
          do 
            if [ $name == "${{github.event.sender.login}}" ]
            then
              exit 0
            fi
          done
          echo "user ${{github.event.sender.login}} is not allowed to run functional tests Action"
          exit 1

